name: Cypress End-2-End tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Encode workers
        run: npm run encode:worker
      - name: Cypress tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: example
          start: npm start
          wait-on: http://localhost:1234
